/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class distribusi extends javax.swing.JFrame {

    /**
     * Creates new form distribusi
     */
    public distribusi() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getIceMin() {
        return IceMin;
    }

    public JButton getIcePlus() {
        return IcePlus;
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    public JLabel getIceJumlah() {
        return iceJumlah;
    }

    public JLabel getMarningJumlah() {
        return marningJumlah;
    }

    public JButton getMarningMin() {
        return marningMin;
    }

    public JButton getMarningPlus() {
        return marningPlus;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marningJumlah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marningPlus = new javax.swing.JButton();
        marningMin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        IceMin = new javax.swing.JButton();
        iceJumlah = new javax.swing.JLabel();
        IcePlus = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marningJumlah.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        marningJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marningJumlah.setText("Jumlah");
        getContentPane().add(marningJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 100, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        jLabel2.setText("DISTRIBUSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Koin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, 60, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Marning");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 60, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Marning");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 110, -1));

        marningPlus.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        marningPlus.setText("+");
        marningPlus.setFocusable(false);
        getContentPane().add(marningPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 60, 50));

        marningMin.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        marningMin.setText("-");
        marningMin.setFocusable(false);
        getContentPane().add(marningMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 60, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Ice Cream Jagung");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 230, -1));

        IceMin.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        IceMin.setText("-");
        IceMin.setFocusable(false);
        getContentPane().add(IceMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 60, 50));

        iceJumlah.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        iceJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iceJumlah.setText("Jumlah");
        getContentPane().add(iceJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 100, 50));

        IcePlus.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        IcePlus.setText("+");
        IcePlus.setFocusable(false);
        getContentPane().add(IcePlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 60, 50));

        btnOk.setText("OK");
        btnOk.setFocusable(false);
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 110, 60));

        btnBatal.setText("BATAL");
        btnBatal.setFocusable(false);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 110, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distribusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distribusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distribusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distribusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distribusi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IceMin;
    private javax.swing.JButton IcePlus;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel iceJumlah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel marningJumlah;
    private javax.swing.JButton marningMin;
    private javax.swing.JButton marningPlus;
    // End of variables declaration//GEN-END:variables
}
