/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class gudang extends javax.swing.JFrame {

    /**
     * Creates new form gudang
     */
    public gudang() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JLabel getIconItem1() {
        return iconItem1;
    }

    public JLabel getIconItem2() {
        return iconItem2;
    }

    public JLabel getIconItem3() {
        return iconItem3;
    }

    public JLabel getIconItem4() {
        return iconItem4;
    }

    public JLabel getLblBibit() {
        return lblBibit;
    }

    public JLabel getLblGaram() {
        return lblGaram;
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }

    public JLabel getLblMinyakGoreng() {
        return lblMinyakGoreng;
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        lblMinyakGoreng = new javax.swing.JLabel();
        lblGaram = new javax.swing.JLabel();
        lblBibit = new javax.swing.JLabel();
        lblJagung = new javax.swing.JLabel();
        iconItem4 = new javax.swing.JLabel();
        iconItem1 = new javax.swing.JLabel();
        iconItem2 = new javax.swing.JLabel();
        iconItem3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/jagagudang2.gif"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 300, 360));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClose.png"))); // NOI18N
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        btnKembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClosehover.png"))); // NOI18N
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 140, 130));

        lblMinyakGoreng.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblMinyakGoreng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinyakGoreng.setText("item4");
        getContentPane().add(lblMinyakGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 422, 120, 30));

        lblGaram.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblGaram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGaram.setText("item3");
        getContentPane().add(lblGaram, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 424, 120, 30));

        lblBibit.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBibit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBibit.setText("item2");
        getContentPane().add(lblBibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 423, 120, 30));

        lblJagung.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJagung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagung.setText("item1");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 423, 120, 30));

        iconItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/gudangminyak goreng.png"))); // NOI18N
        getContentPane().add(iconItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 180, 210));

        iconItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/gudangjagung.png"))); // NOI18N
        getContentPane().add(iconItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 150, 210));

        iconItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/gudangbibitJagung.png"))); // NOI18N
        getContentPane().add(iconItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 160, 210));

        iconItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/gudanggaram.png"))); // NOI18N
        getContentPane().add(iconItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 160, 220));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/kotakDasar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 900, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/gudangbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel iconItem1;
    private javax.swing.JLabel iconItem2;
    private javax.swing.JLabel iconItem3;
    private javax.swing.JLabel iconItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBibit;
    private javax.swing.JLabel lblGaram;
    private javax.swing.JLabel lblJagung;
    private javax.swing.JLabel lblMinyakGoreng;
    // End of variables declaration//GEN-END:variables
}
