/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class helpToko extends javax.swing.JFrame {

    /**
     * Creates new form helpToko
     */
    public helpToko() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JButton getBtnKanan() {
        return btnKanan;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnKiri() {
        return btnKiri;
    }

    public JLabel getLblGambar() {
        return lblGambar;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        btnKiri = new javax.swing.JButton();
        btnKanan = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petunjuk/sayaPaham.png"))); // NOI18N
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        btnKembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petunjuk/sayaPaham hover.png"))); // NOI18N
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 570, 200, 90));

        btnKiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petunjuk/kiri.png"))); // NOI18N
        btnKiri.setBorderPainted(false);
        btnKiri.setContentAreaFilled(false);
        btnKiri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKiri.setFocusable(false);
        btnKiri.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petunjuk/kiriHover.png"))); // NOI18N
        getContentPane().add(btnKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 60, 250));

        btnKanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petunjuk/kanan.png"))); // NOI18N
        btnKanan.setBorderPainted(false);
        btnKanan.setContentAreaFilled(false);
        btnKanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKanan.setFocusable(false);
        btnKanan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petunjuk/kananHover.png"))); // NOI18N
        getContentPane().add(btnKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 290, 60, 250));
        getContentPane().add(lblGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helpToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKanan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKiri;
    private javax.swing.JLabel lblGambar;
    // End of variables declaration//GEN-END:variables
}
