/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(this);
    }


    public JButton getBtnDistribusi() {
        return btnGudang;
    }
    public JButton getBtnGudang() {
        return btnGudang;
    }
    
    public JButton getBtnKoperasi() {
        return btnKoperasi;
    }

    public JButton getBtnRuProduksi() {
        return btnRuProduksi;
    }

    public JButton getBtnSawah1() {
        return btnSawah;
    }



    public JButton getBtnToko() {
        return btnToko;
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSawah = new javax.swing.JButton();
        btnToko = new javax.swing.JButton();
        btnKoperasi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        btnToko = new javax.swing.JButton();
        btnKoperasi = new javax.swing.JButton();
        btnSawah1 = new javax.swing.JButton();
        btnGudang = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRuProduksi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jagung.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 23, 50, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/uang.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/marning.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/scorebar.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rumah.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnSawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah.png"))); // NOI18N
        btnSawah.setBorderPainted(false);
        btnSawah.setContentAreaFilled(false);
        btnSawah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawahHover.png"))); // NOI18N
        getContentPane().add(btnSawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));btnToko.setText("Toko");
        btnToko.setFocusable(false);
        getContentPane().add(btnToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 120, 130));

        btnKoperasi.setText("Koperasi");
        btnKoperasi.setFocusable(false);
        getContentPane().add(btnKoperasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 140, 160));

        btnSawah1.setText("sawah 1");
        btnSawah1.setFocusable(false);
        getContentPane().add(btnSawah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 100));

        btnGudang.setText("Gudang");
        btnGudang.setFocusable(false);
        getContentPane().add(btnGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 170, 150));

        btnRuProduksi.setText("Rumah Produksi");
        btnRuProduksi.setFocusable(false);
        getContentPane().add(btnRuProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 190, 160));

        btnToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/toko.png"))); // NOI18N
        btnToko.setBorderPainted(false);
        btnToko.setContentAreaFilled(false);
        btnToko.setFocusable(false);
        btnToko.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tokoHover.png"))); // NOI18N
        getContentPane().add(btnToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 310, 240));

        btnKoperasi.setBackground(new java.awt.Color(254, 254, 254));
        btnKoperasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/koperasi.png"))); // NOI18N
        btnKoperasi.setText("\n");
        btnKoperasi.setBorderPainted(false);
        btnKoperasi.setContentAreaFilled(false);
        btnKoperasi.setFocusable(false);
        btnKoperasi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/koperasiHover.png"))); // NOI18N
        getContentPane().add(btnKoperasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 300, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        btnGudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gudang.png"))); // NOI18N
        btnGudang.setBorderPainted(false);
        btnGudang.setContentAreaFilled(false);
        btnGudang.setFocusable(false);
        btnGudang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gudangHover.png"))); // NOI18N
        getContentPane().add(btnGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 350, 290));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pohon cemara.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));
        btnLogOut.setText("Logout");
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 40));

        btnRuProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik.png"))); // NOI18N
        btnRuProduksi.setBorderPainted(false);
        btnRuProduksi.setContentAreaFilled(false);
        btnRuProduksi.setFocusable(false);
        btnRuProduksi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrikHover.png"))); // NOI18N
        getContentPane().add(btnRuProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 330, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mapKosong.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGudang;
    private javax.swing.JButton btnKoperasi;
    private javax.swing.JButton btnRuProduksi;
    private javax.swing.JButton btnSawah;
    private javax.swing.JButton btnSawah1;
    private javax.swing.JButton btnToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
