/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }    

    public JButton getBtnGudang() {
        return btnGudang;
    }

    public JButton getBtnKoperasi() {
        return btnKoperasi;
    }

    public JButton getBtnRuProduksi() {
        return btnRuProduksi;
    }

    public JButton getBtnSawah1() {
        return btnSawah1;
    }

    public JButton getBtnToko() {
        return btnToko;
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public JLabel getLabelUsername() {
        return labelUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJagung = new javax.swing.JLabel();
        lblKoin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statusBar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnToko = new javax.swing.JButton();
        btnGudang = new javax.swing.JButton();
        btnKoperasi = new javax.swing.JButton();
        btnSawah1 = new javax.swing.JButton();
        btnRuProduksi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJagung.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJagung.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJagung.setText("Jagung");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 120, 30));

        lblKoin.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKoin.setText("Koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, 100, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Produk");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 110, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 620, 60, 60));

        labelUsername.setFont(new java.awt.Font("Bebas Neue", 0, 30)); // NOI18N
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername.setText("username");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 22, 200, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/uang.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 70, 80));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/marning.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 80, 90));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/jagung.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 60, 70));

        statusBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/scorebar.png"))); // NOI18N
        getContentPane().add(statusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohon cemara.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 510, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        btnToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/toko.png"))); // NOI18N
        btnToko.setBorderPainted(false);
        btnToko.setContentAreaFilled(false);
        btnToko.setFocusable(false);
        btnToko.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/tokoHover.png"))); // NOI18N
        getContentPane().add(btnToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 440, 240));

        btnGudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/gudang.png"))); // NOI18N
        btnGudang.setBorderPainted(false);
        btnGudang.setContentAreaFilled(false);
        btnGudang.setFocusable(false);
        btnGudang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/gudangHover.png"))); // NOI18N
        getContentPane().add(btnGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 450, 300));

        btnKoperasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/koperasi.png"))); // NOI18N
        btnKoperasi.setBorderPainted(false);
        btnKoperasi.setContentAreaFilled(false);
        btnKoperasi.setFocusable(false);
        btnKoperasi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/koperasiHover.png"))); // NOI18N
        getContentPane().add(btnKoperasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 280, 270));

        btnSawah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/sawah.png"))); // NOI18N
        btnSawah1.setBorderPainted(false);
        btnSawah1.setContentAreaFilled(false);
        btnSawah1.setFocusable(false);
        btnSawah1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/sawahHover.png"))); // NOI18N
        getContentPane().add(btnSawah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        btnRuProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/pabrik.png"))); // NOI18N
        btnRuProduksi.setBorderPainted(false);
        btnRuProduksi.setContentAreaFilled(false);
        btnRuProduksi.setFocusable(false);
        btnRuProduksi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/pabrikHover.png"))); // NOI18N
        getContentPane().add(btnRuProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 320, 280));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohongajelas.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohon cemara.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/rumah.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/pohon cemara.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/tier1/mapKosong.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGudang;
    private javax.swing.JButton btnKoperasi;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRuProduksi;
    private javax.swing.JButton btnSawah1;
    private javax.swing.JButton btnToko;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel lblJagung;
    private javax.swing.JLabel lblKoin;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
