/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class koperasi extends javax.swing.JFrame {

    /**
     * Creates new form koperasi
     */
    public koperasi() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnItem1() {
        return btnItem1;
    }

    public JButton getBtnItem2() {
        return btnItem2;
    }

    public JButton getBtnItem3() {
        return btnItem3;
    }

    public JButton getBtnItem4() {
        return btnItem4;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JLabel getLblGaram() {
        return lblGaram;
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }

    public JLabel getLblMinyak() {
        return lblMinyak;
    }

    public JLabel getLblBibit() {
        return lblBibit;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnItem1 = new javax.swing.JButton();
        btnItem2 = new javax.swing.JButton();
        btnItem3 = new javax.swing.JButton();
        btnItem4 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblMinyak = new javax.swing.JLabel();
        lblKoin = new javax.swing.JLabel();
        lblJagung = new javax.swing.JLabel();
        lblGaram = new javax.swing.JLabel();
        lblBibit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KOPERASI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 130, 40));

        btnItem1.setText("item 1");
        btnItem1.setFocusable(false);
        getContentPane().add(btnItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, 150));

        btnItem2.setText("item 2");
        btnItem2.setFocusable(false);
        getContentPane().add(btnItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 150, 150));

        btnItem3.setText("item 3");
        btnItem3.setFocusable(false);
        getContentPane().add(btnItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 180, 150));

        btnItem4.setText("item 4");
        btnItem4.setFocusable(false);
        getContentPane().add(btnItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 350, 150));

        btnKembali.setText("KEMBALI");
        btnKembali.setFocusable(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 120, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gambar Orang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 120, 160));

        lblMinyak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinyak.setText("minyak goreng");
        getContentPane().add(lblMinyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 80, 20));

        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKoin.setText("koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 50, 20));

        lblJagung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagung.setText("jagung");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 50, 20));

        lblGaram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGaram.setText("garam");
        getContentPane().add(lblGaram, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 50, 20));

        lblBibit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBibit.setText("bibit");
        getContentPane().add(lblBibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koperasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItem1;
    private javax.swing.JButton btnItem2;
    private javax.swing.JButton btnItem3;
    private javax.swing.JButton btnItem4;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBibit;
    private javax.swing.JLabel lblGaram;
    private javax.swing.JLabel lblJagung;
    private javax.swing.JLabel lblKoin;
    private javax.swing.JLabel lblMinyak;
    // End of variables declaration//GEN-END:variables
}
