/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;

/**
 *
 * @author Rangora
 */
public class koperasi extends javax.swing.JFrame {

    /**
     * Creates new form koperasi
     */
    public koperasi() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnItem1() {
        return btnItem1;
    }

    public JButton getBtnItem10() {
        return btnItem10;
    }

    public JButton getBtnItem2() {
        return btnItem2;
    }

    public JButton getBtnItem3() {
        return btnItem3;
    }

    public JButton getBtnItem4() {
        return btnItem4;
    }

    public JButton getBtnItem5() {
        return btnItem5;
    }

    public JButton getBtnItem6() {
        return btnItem6;
    }

    public JButton getBtnItem7() {
        return btnItem7;
    }

    public JButton getBtnItem8() {
        return btnItem8;
    }

    public JButton getBtnItem9() {
        return btnItem9;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnNext() {
        return btnNext;
    }

    public JButton getBtnPrevious() {
        return btnPrevious;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnItem5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnItem1 = new javax.swing.JButton();
        btnItem2 = new javax.swing.JButton();
        btnItem3 = new javax.swing.JButton();
        btnItem4 = new javax.swing.JButton();
        btnItem6 = new javax.swing.JButton();
        btnItem7 = new javax.swing.JButton();
        btnItem8 = new javax.swing.JButton();
        btnItem9 = new javax.swing.JButton();
        btnItem10 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnItem5.setText("item 5");
        btnItem5.setFocusable(false);
        getContentPane().add(btnItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 150, 150));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KOPERASI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 130, 40));

        btnItem1.setText("item 1");
        btnItem1.setFocusable(false);
        getContentPane().add(btnItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, 150));

        btnItem2.setText("item 2");
        btnItem2.setFocusable(false);
        getContentPane().add(btnItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 150, 150));

        btnItem3.setText("item 3");
        btnItem3.setFocusable(false);
        getContentPane().add(btnItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 150, 150));

        btnItem4.setText("item 4");
        btnItem4.setFocusable(false);
        getContentPane().add(btnItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 150, 150));

        btnItem6.setText("item 6");
        btnItem6.setFocusable(false);
        getContentPane().add(btnItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, 150));

        btnItem7.setText("item 7");
        btnItem7.setFocusable(false);
        getContentPane().add(btnItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 150, 150));

        btnItem8.setText("item 8");
        btnItem8.setFocusable(false);
        getContentPane().add(btnItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 150, 150));

        btnItem9.setText("item 9");
        btnItem9.setFocusable(false);
        getContentPane().add(btnItem9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 150, 150));

        btnItem10.setText("item 10");
        btnItem10.setFocusable(false);
        getContentPane().add(btnItem10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 150, 150));

        btnKembali.setText("KEMBALI");
        btnKembali.setFocusable(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 150, 60));

        btnNext.setText(">");
        btnNext.setFocusable(false);
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 70, 70));

        btnPrevious.setText("<");
        btnPrevious.setFocusable(false);
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 70, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gambar Orang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 120, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koperasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItem1;
    private javax.swing.JButton btnItem10;
    private javax.swing.JButton btnItem2;
    private javax.swing.JButton btnItem3;
    private javax.swing.JButton btnItem4;
    private javax.swing.JButton btnItem5;
    private javax.swing.JButton btnItem6;
    private javax.swing.JButton btnItem7;
    private javax.swing.JButton btnItem8;
    private javax.swing.JButton btnItem9;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
