/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rangora
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setLocationRelativeTo(this);
        usernameFrame.setLocationRelativeTo(this);
    }

    public JButton getBtnLoad() {
        return btnLoad;
    }

    public JButton getBtnKeluar() {
        return btnKeluar;
    }

    public JButton getBtnMulai() {
        return btnMulai;
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    public JTextField getFieldUsername() {
        return fieldUsername;
    }

    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public JFrame getUsernameFrame() {
        return usernameFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        fieldUsername = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        btnMulai = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        usernameFrame.setMinimumSize(new java.awt.Dimension(400, 300));
        usernameFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERNAME");
        usernameFrame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 70, 30));

        btnBatal.setText("BATAL");
        btnBatal.setFocusable(false);
        usernameFrame.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, 50));

        btnOk.setText("OK");
        btnOk.setFocusable(false);
        usernameFrame.getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 100, 50));

        fieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameFrame.getContentPane().add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 220, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setText("Keluar Game");
        btnKeluar.setFocusable(false);
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 230, 90));

        btnMulai.setText("Mulai Baru");
        btnMulai.setFocusable(false);
        getContentPane().add(btnMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 230, 90));

        jButton3.setText("jButton1");
        jButton3.setFocusable(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 230, 90));

        btnLoad.setText("Load");
        btnLoad.setFocusable(false);
        getContentPane().add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 230, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnMulai;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFrame usernameFrame;
    // End of variables declaration//GEN-END:variables
}
