/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class pabrik extends javax.swing.JFrame {

    /**
     * Creates new form pabrik
     */
    public pabrik() {
        initComponents();
        this.setLocationRelativeTo(null);
        frameP1.setLocationRelativeTo(null);
        frameP2.setLocationRelativeTo(null);
        frameP3.setLocationRelativeTo(null);
        frameP4.setLocationRelativeTo(null);
    }

    public JButton getBtnBatalP1() {
        return btnBatalP1;
    }

    public JButton getBtnBatalP2() {
        return btnBatalP2;
    }

    public JButton getBtnBatalP3() {
        return btnBatalP3;
    }

    public JButton getBtnBatalP4() {
        return btnBatalP4;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnKurangGP3() {
        return btnKurangGP3;
    }

    public JButton getBtnKurangJRP3() {
        return btnKurangJRP3;
    }

    public JButton getBtnKurangP1() {
        return btnKurangP1;
    }

    public JButton getBtnKurangP2() {
        return btnKurangP2;
    }

    public JButton getBtnKurangP4() {
        return btnKurangP4;
    }

    public JButton getBtnMulaiP1() {
        return btnMulaiP1;
    }

    public JButton getBtnMulaiP2() {
        return btnMulaiP2;
    }

    public JButton getBtnMulaiP3() {
        return btnMulaiP3;
    }

    public JButton getBtnMulaiP4() {
        return btnMulaiP4;
    }

    public JButton getBtnProses1() {
        return btnProses1;
    }

    public JButton getBtnProses2() {
        return btnProses2;
    }

    public JButton getBtnProses3() {
        return btnProses3;
    }

    public JButton getBtnProses4() {
        return btnProses4;
    }

    public JButton getBtnTambahGP3() {
        return btnTambahGP3;
    }

    public JButton getBtnTambahJRP3() {
        return btnTambahJRP3;
    }

    public JButton getBtnTambahKaryawan() {
        return btnTambahKaryawan;
    }

    public JButton getBtnTambahP1() {
        return btnTambahP1;
    }

    public JButton getBtnTambahP2() {
        return btnTambahP2;
    }

    public JButton getBtnTambahP4() {
        return btnTambahP4;
    }

    public JFrame getFrameP1() {
        return frameP1;
    }

    public JFrame getFrameP2() {
        return frameP2;
    }

    public JFrame getFrameP3() {
        return frameP3;
    }

    public JFrame getFrameP4() {
        return frameP4;
    }

    public JLabel getLblBanyakGP3() {
        return lblBanyakGP3;
    }

    public JLabel getLblBanyakJRP3() {
        return lblBanyakJRP3;
    }

    public JLabel getLblBanyakP1() {
        return lblBanyakP1;
    }

    public JLabel getLblBanyakP2() {
        return lblBanyakP2;
    }

    public JLabel getLblBanyakP4() {
        return lblBanyakP4;
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }

    public JLabel getLblJagungBumbu() {
        return lblJagungBumbu;
    }

    public JLabel getLblJagungCuci() {
        return lblJagungCuci;
    }

    public JLabel getLblJagungRendam() {
        return lblJagungRendam;
    }

    public JLabel getLblJumlahKaryawan() {
        return lblJumlahKaryawan;
    }

    public JLabel getLblMarning() {
        return lblMarning;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameP1 = new javax.swing.JFrame();
        btnBatalP1 = new javax.swing.JButton();
        lblBanyakK1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMulaiP1 = new javax.swing.JButton();
        btnKurangP1 = new javax.swing.JButton();
        btnTambahP1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblBanyakP1 = new javax.swing.JLabel();
        frameP2 = new javax.swing.JFrame();
        btnBatalP2 = new javax.swing.JButton();
        lblBanyakP2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTambahP2 = new javax.swing.JButton();
        btnMulaiP2 = new javax.swing.JButton();
        btnKurangP2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblMaxP2 = new javax.swing.JLabel();
        frameP3 = new javax.swing.JFrame();
        btnBatalP3 = new javax.swing.JButton();
        lblBanyakGP3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMulaiP3 = new javax.swing.JButton();
        btnKurangGP3 = new javax.swing.JButton();
        btnTambahGP3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnKurangJRP3 = new javax.swing.JButton();
        lblBanyakJRP3 = new javax.swing.JLabel();
        btnTambahJRP3 = new javax.swing.JButton();
        lblBanyakJRP3Max = new javax.swing.JLabel();
        lblBanyakGP4Max = new javax.swing.JLabel();
        frameP4 = new javax.swing.JFrame();
        btnBatalP4 = new javax.swing.JButton();
        lblBanyakP4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnTambahP4 = new javax.swing.JButton();
        btnMulaiP4 = new javax.swing.JButton();
        btnKurangP4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnProses2 = new javax.swing.JButton();
        btnProses1 = new javax.swing.JButton();
        btnProses4 = new javax.swing.JButton();
        btnProses3 = new javax.swing.JButton();
        lblMarning = new javax.swing.JLabel();
        lblJagung = new javax.swing.JLabel();
        lblJagungBumbu = new javax.swing.JLabel();
        lblJagungCuci = new javax.swing.JLabel();
        lblJagungRendam = new javax.swing.JLabel();
        btnTambahKaryawan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblJumlahKaryawan = new javax.swing.JLabel();

        frameP1.setMinimumSize(new java.awt.Dimension(600, 500));
        frameP1.setPreferredSize(new java.awt.Dimension(600, 500));
        frameP1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP1.setText("batal");
        btnBatalP1.setFocusable(false);
        frameP1.getContentPane().add(btnBatalP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 50));

        lblBanyakK1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakK1.setText("/ 30");
        frameP1.getContentPane().add(lblBanyakK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 40, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Proses 1 (Cuci Jagung)");
        frameP1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 340, 40));

        btnMulaiP1.setText("Mulai Proses");
        btnMulaiP1.setFocusable(false);
        frameP1.getContentPane().add(btnMulaiP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 220, 60));

        btnKurangP1.setText("-");
        btnKurangP1.setFocusable(false);
        frameP1.getContentPane().add(btnKurangP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 70, 60));

        btnTambahP1.setText("+");
        btnTambahP1.setFocusable(false);
        frameP1.getContentPane().add(btnTambahP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 70, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jagung");
        frameP1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, 40));

        lblBanyakP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP1.setText("1");
        frameP1.getContentPane().add(lblBanyakP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 40, 40));

        frameP2.setMinimumSize(new java.awt.Dimension(600, 500));
        frameP2.setPreferredSize(new java.awt.Dimension(600, 500));
        frameP2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP2.setText("Batal");
        btnBatalP2.setFocusPainted(false);
        frameP2.getContentPane().add(btnBatalP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        lblBanyakP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP2.setText("1");
        frameP2.getContentPane().add(lblBanyakP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 40, 60));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Proses 2 (Rendam jagung)");
        frameP2.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 370, 70));

        btnTambahP2.setText("+");
        btnTambahP2.setFocusPainted(false);
        frameP2.getContentPane().add(btnTambahP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, 60));

        btnMulaiP2.setText("Mulai Proses");
        btnMulaiP2.setFocusPainted(false);
        frameP2.getContentPane().add(btnMulaiP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 220, 60));

        btnKurangP2.setText("-");
        btnKurangP2.setFocusPainted(false);
        frameP2.getContentPane().add(btnKurangP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 70, 60));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jagung cuci");
        frameP2.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, 70));

        lblMaxP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaxP2.setText("/ 30");
        frameP2.getContentPane().add(lblMaxP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 40, 60));

        frameP3.setMaximumSize(new java.awt.Dimension(600, 500));
        frameP3.setMinimumSize(new java.awt.Dimension(600, 500));
        frameP3.setPreferredSize(new java.awt.Dimension(600, 500));
        frameP3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP3.setText("Batal");
        btnBatalP3.setFocusable(false);
        frameP3.getContentPane().add(btnBatalP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 50));

        lblBanyakGP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakGP3.setText("1");
        frameP3.getContentPane().add(lblBanyakGP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 40, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Proses 3 (Pemberian Bumbu)");
        frameP3.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 330, 60));

        btnMulaiP3.setText("Mulai Proses");
        btnMulaiP3.setFocusable(false);
        frameP3.getContentPane().add(btnMulaiP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 230, 60));

        btnKurangGP3.setText("-");
        btnKurangGP3.setFocusable(false);
        frameP3.getContentPane().add(btnKurangGP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 70, 60));

        btnTambahGP3.setText("+");
        btnTambahGP3.setFocusable(false);
        frameP3.getContentPane().add(btnTambahGP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 70, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Garam");
        frameP3.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 60));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Jagung Rendam");
        frameP3.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, 60));

        btnKurangJRP3.setText("-");
        btnKurangJRP3.setFocusable(false);
        frameP3.getContentPane().add(btnKurangJRP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, 60));

        lblBanyakJRP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakJRP3.setText("1");
        frameP3.getContentPane().add(lblBanyakJRP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 40, 60));

        btnTambahJRP3.setText("+");
        btnTambahJRP3.setFocusable(false);
        frameP3.getContentPane().add(btnTambahJRP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 70, 60));

        lblBanyakJRP3Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakJRP3Max.setText("/ 20");
        frameP3.getContentPane().add(lblBanyakJRP3Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 40, 60));

        lblBanyakGP4Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakGP4Max.setText("/  6");
        frameP3.getContentPane().add(lblBanyakGP4Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 40, 60));

        frameP4.setMinimumSize(new java.awt.Dimension(600, 500));
        frameP4.setPreferredSize(new java.awt.Dimension(600, 500));
        frameP4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP4.setText("Batal");
        frameP4.getContentPane().add(btnBatalP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 50));

        lblBanyakP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP4.setText("Banyak");
        frameP4.getContentPane().add(lblBanyakP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, 50));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Proses 4 (goreng)");
        frameP4.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 320, 50));

        btnTambahP4.setText("+");
        frameP4.getContentPane().add(btnTambahP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 60, 50));

        btnMulaiP4.setText("Mulai Proses");
        frameP4.getContentPane().add(btnMulaiP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 50));

        btnKurangP4.setText("-");
        frameP4.getContentPane().add(btnKurangP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, 50));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Jagung Bumbu");
        frameP4.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProses2.setText("proses2");
        btnProses2.setFocusable(false);
        btnProses2.setMaximumSize(new java.awt.Dimension(1280, 720));
        btnProses2.setMinimumSize(new java.awt.Dimension(1280, 720));
        btnProses2.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(btnProses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 150, 130));

        btnProses1.setText("proses1");
        btnProses1.setFocusable(false);
        getContentPane().add(btnProses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, 130));

        btnProses4.setText("proses4");
        btnProses4.setFocusable(false);
        btnProses4.setMaximumSize(new java.awt.Dimension(1280, 720));
        btnProses4.setMinimumSize(new java.awt.Dimension(1280, 720));
        btnProses4.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(btnProses4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 150, 130));

        btnProses3.setText("proses3");
        btnProses3.setFocusable(false);
        btnProses3.setMaximumSize(new java.awt.Dimension(1280, 720));
        btnProses3.setMinimumSize(new java.awt.Dimension(1280, 720));
        btnProses3.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(btnProses3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 150, 130));

        lblMarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarning.setText("marning");
        getContentPane().add(lblMarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, 60, 30));

        lblJagung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagung.setText("jagung");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 50, 30));

        lblJagungBumbu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagungBumbu.setText("jagung bumbu");
        getContentPane().add(lblJagungBumbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 30));

        lblJagungCuci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagungCuci.setText("jagung cuci");
        getContentPane().add(lblJagungCuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 70, 30));

        lblJagungRendam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagungRendam.setText("jagung rendam");
        getContentPane().add(lblJagungRendam, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 80, 30));

        btnTambahKaryawan.setText("Tambah Karyawan");
        btnTambahKaryawan.setFocusable(false);
        getContentPane().add(btnTambahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 130, 50));

        btnKembali.setText("Kembali");
        btnKembali.setFocusable(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 60));

        lblJumlahKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahKaryawan.setText("Karyawan");
        getContentPane().add(lblJumlahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pabrik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalP1;
    private javax.swing.JButton btnBatalP2;
    private javax.swing.JButton btnBatalP3;
    private javax.swing.JButton btnBatalP4;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKurangGP3;
    private javax.swing.JButton btnKurangJRP3;
    private javax.swing.JButton btnKurangP1;
    private javax.swing.JButton btnKurangP2;
    private javax.swing.JButton btnKurangP4;
    private javax.swing.JButton btnMulaiP1;
    private javax.swing.JButton btnMulaiP2;
    private javax.swing.JButton btnMulaiP3;
    private javax.swing.JButton btnMulaiP4;
    private javax.swing.JButton btnProses1;
    private javax.swing.JButton btnProses2;
    private javax.swing.JButton btnProses3;
    private javax.swing.JButton btnProses4;
    private javax.swing.JButton btnTambahGP3;
    private javax.swing.JButton btnTambahJRP3;
    private javax.swing.JButton btnTambahKaryawan;
    private javax.swing.JButton btnTambahP1;
    private javax.swing.JButton btnTambahP2;
    private javax.swing.JButton btnTambahP4;
    private javax.swing.JFrame frameP1;
    private javax.swing.JFrame frameP2;
    private javax.swing.JFrame frameP3;
    private javax.swing.JFrame frameP4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBanyakGP3;
    private javax.swing.JLabel lblBanyakGP4Max;
    private javax.swing.JLabel lblBanyakJRP3;
    private javax.swing.JLabel lblBanyakJRP3Max;
    private javax.swing.JLabel lblBanyakK1;
    private javax.swing.JLabel lblBanyakP1;
    private javax.swing.JLabel lblBanyakP2;
    private javax.swing.JLabel lblBanyakP4;
    private javax.swing.JLabel lblJagung;
    private javax.swing.JLabel lblJagungBumbu;
    private javax.swing.JLabel lblJagungCuci;
    private javax.swing.JLabel lblJagungRendam;
    private javax.swing.JLabel lblJumlahKaryawan;
    private javax.swing.JLabel lblMarning;
    private javax.swing.JLabel lblMaxP2;
    // End of variables declaration//GEN-END:variables
}
