/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class pabrik extends javax.swing.JFrame {

    /**
     * Creates new form pabrik
     */
    public pabrik() {
        initComponents();
        this.setLocationRelativeTo(null);
        frameP1.setLocationRelativeTo(null);
        frameP2.setLocationRelativeTo(null);
        frameP3.setLocationRelativeTo(null);
        frameP4.setLocationRelativeTo(null);
    }

    public JButton getBtnBatalP1() {
        return btnBatalP1;
    }

    public JButton getBtnBatalP2() {
        return btnBatalP2;
    }

    public JButton getBtnBatalP3() {
        return btnBatalP3;
    }

    public JButton getBtnBatalP4() {
        return btnBatalP4;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnKurangGP3() {
        return btnKurangGP3;
    }

    public JButton getBtnKurangJRP3() {
        return btnKurangJRP3;
    }

    public JButton getBtnKurangP1() {
        return btnKurangP1;
    }

    public JButton getBtnKurangP2() {
        return btnKurangP2;
    }

    public JButton getBtnKurangP4() {
        return btnKurangP4;
    }

    public JButton getBtnMulaiP1() {
        return btnMulaiP1;
    }

    public JButton getBtnMulaiP2() {
        return btnMulaiP2;
    }

    public JButton getBtnMulaiP3() {
        return btnMulaiP3;
    }

    public JButton getBtnMulaiP4() {
        return btnMulaiP4;
    }

    public JButton getBtnProses1() {
        return btnProses1;
    }

    public JButton getBtnProses2() {
        return btnProses2;
    }

    public JButton getBtnProses3() {
        return btnProses3;
    }

    public JButton getBtnProses4() {
        return btnProses4;
    }

    public JButton getBtnTambahGP3() {
        return btnTambahGP3;
    }

    public JButton getBtnTambahJRP3() {
        return btnTambahJRP3;
    }

    public JButton getBtnTambahKaryawan() {
        return btnTambahKaryawan;
    }

    public JButton getBtnTambahP1() {
        return btnTambahP1;
    }

    public JButton getBtnTambahP2() {
        return btnTambahP2;
    }

    public JButton getBtnTambahP4() {
        return btnTambahP4;
    }

    public JFrame getFrameP1() {
        return frameP1;
    }

    public JFrame getFrameP2() {
        return frameP2;
    }

    public JFrame getFrameP3() {
        return frameP3;
    }

    public JFrame getFrameP4() {
        return frameP4;
    }

    public JLabel getLblBanyakGP3() {
        return lblBanyakGP3;
    }

    public JLabel getLblBanyakJRP3() {
        return lblBanyakJRP3;
    }

    public JLabel getLblBanyakP1() {
        return lblBanyakP1;
    }

    public JLabel getLblBanyakP2() {
        return lblBanyakP2;
    }

    public JLabel getLblBanyakP4() {
        return lblBanyakP4;
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }

    public JLabel getLblJagungBumbu() {
        return lblJagungBumbu;
    }

    public JLabel getLblJagungCuci() {
        return lblJagungCuci;
    }

    public JLabel getLblJagungRendam() {
        return lblJagungRendam;
    }

    public JLabel getLblJumlahKaryawan() {
        return lblJumlahKaryawan;
    }

    public JLabel getLblMarning() {
        return lblMarning;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameP1 = new javax.swing.JFrame();
        btnBatalP1 = new javax.swing.JButton();
        lblBanyakK1 = new javax.swing.JLabel();
        btnMulaiP1 = new javax.swing.JButton();
        btnKurangP1 = new javax.swing.JButton();
        btnTambahP1 = new javax.swing.JButton();
        lblBanyakP1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        frameP2 = new javax.swing.JFrame();
        btnBatalP2 = new javax.swing.JButton();
        lblBanyakP2 = new javax.swing.JLabel();
        btnTambahP2 = new javax.swing.JButton();
        btnMulaiP2 = new javax.swing.JButton();
        btnKurangP2 = new javax.swing.JButton();
        lblMaxP2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        frameP3 = new javax.swing.JFrame();
        btnBatalP3 = new javax.swing.JButton();
        lblBanyakGP3 = new javax.swing.JLabel();
        btnMulaiP3 = new javax.swing.JButton();
        btnKurangGP3 = new javax.swing.JButton();
        btnTambahGP3 = new javax.swing.JButton();
        btnKurangJRP3 = new javax.swing.JButton();
        lblBanyakJRP3 = new javax.swing.JLabel();
        btnTambahJRP3 = new javax.swing.JButton();
        lblBanyakJRP3Max = new javax.swing.JLabel();
        lblBanyakGP4Max = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        frameP4 = new javax.swing.JFrame();
        btnBatalP4 = new javax.swing.JButton();
        lblBanyakP4 = new javax.swing.JLabel();
        btnTambahP4 = new javax.swing.JButton();
        btnMulaiP4 = new javax.swing.JButton();
        btnKurangP4 = new javax.swing.JButton();
        lblBanyakP5Max = new javax.swing.JLabel();
        btnKurangMinyak = new javax.swing.JButton();
        lblBanyakMinyak = new javax.swing.JLabel();
        lblBanyakP5Max1 = new javax.swing.JLabel();
        btnTambahMinyak = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnProses1 = new javax.swing.JButton();
        btnProses4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnProses3 = new javax.swing.JButton();
        btnProses2 = new javax.swing.JButton();
        lblMarning = new javax.swing.JLabel();
        lblJagung = new javax.swing.JLabel();
        lblJagungBumbu = new javax.swing.JLabel();
        lblJagungCuci = new javax.swing.JLabel();
        lblJagungRendam = new javax.swing.JLabel();
        btnTambahKaryawan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblJumlahKaryawan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        frameP1.setMinimumSize(new java.awt.Dimension(643, 530));
        frameP1.setUndecorated(true);
        frameP1.setResizable(false);
        frameP1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClose.png"))); // NOI18N
        btnBatalP1.setBorderPainted(false);
        btnBatalP1.setContentAreaFilled(false);
        btnBatalP1.setFocusable(false);
        btnBatalP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBatalP1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClosehover.png"))); // NOI18N
        frameP1.getContentPane().add(btnBatalP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -13, 110, 130));

        lblBanyakK1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakK1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakK1.setText("/ 30");
        frameP1.getContentPane().add(lblBanyakK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 40, 40));

        btnMulaiP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOK.png"))); // NOI18N
        btnMulaiP1.setBorderPainted(false);
        btnMulaiP1.setContentAreaFilled(false);
        btnMulaiP1.setFocusable(false);
        btnMulaiP1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOKhover.png"))); // NOI18N
        frameP1.getContentPane().add(btnMulaiP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 290, 100));

        btnKurangP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinus.png"))); // NOI18N
        btnKurangP1.setBorderPainted(false);
        btnKurangP1.setContentAreaFilled(false);
        btnKurangP1.setFocusable(false);
        btnKurangP1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinushover.png"))); // NOI18N
        frameP1.getContentPane().add(btnKurangP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 157, 60, 60));

        btnTambahP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlus.png"))); // NOI18N
        btnTambahP1.setBorderPainted(false);
        btnTambahP1.setContentAreaFilled(false);
        btnTambahP1.setFocusable(false);
        btnTambahP1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlushover.png"))); // NOI18N
        frameP1.getContentPane().add(btnTambahP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 50, 50));

        lblBanyakP1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP1.setText("1");
        frameP1.getContentPane().add(lblBanyakP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 40, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tambahBahanProses1.png"))); // NOI18N
        frameP1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        frameP2.setMinimumSize(new java.awt.Dimension(643, 530));
        frameP2.setUndecorated(true);
        frameP2.setResizable(false);
        frameP2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClose.png"))); // NOI18N
        btnBatalP2.setBorderPainted(false);
        btnBatalP2.setContentAreaFilled(false);
        btnBatalP2.setFocusPainted(false);
        btnBatalP2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBatalP2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBatalP2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClosehover.png"))); // NOI18N
        frameP2.getContentPane().add(btnBatalP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -10, 130, 130));

        lblBanyakP2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP2.setText("1");
        frameP2.getContentPane().add(lblBanyakP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, 60));

        btnTambahP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlus.png"))); // NOI18N
        btnTambahP2.setBorderPainted(false);
        btnTambahP2.setContentAreaFilled(false);
        btnTambahP2.setFocusPainted(false);
        btnTambahP2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlushover.png"))); // NOI18N
        frameP2.getContentPane().add(btnTambahP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 50, 50));

        btnMulaiP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOK.png"))); // NOI18N
        btnMulaiP2.setBorderPainted(false);
        btnMulaiP2.setContentAreaFilled(false);
        btnMulaiP2.setFocusPainted(false);
        btnMulaiP2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOKhover.png"))); // NOI18N
        frameP2.getContentPane().add(btnMulaiP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 300, 110));

        btnKurangP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinus.png"))); // NOI18N
        btnKurangP2.setBorderPainted(false);
        btnKurangP2.setContentAreaFilled(false);
        btnKurangP2.setFocusPainted(false);
        btnKurangP2.setFocusable(false);
        btnKurangP2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinushover.png"))); // NOI18N
        frameP2.getContentPane().add(btnKurangP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 50));

        lblMaxP2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblMaxP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaxP2.setText("/ 30");
        frameP2.getContentPane().add(lblMaxP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 40, 60));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tambahBahanProses2.png"))); // NOI18N
        frameP2.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 530));

        frameP3.setMinimumSize(new java.awt.Dimension(643, 530));
        frameP3.setUndecorated(true);
        frameP3.setResizable(false);
        frameP3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClose.png"))); // NOI18N
        btnBatalP3.setBorderPainted(false);
        btnBatalP3.setContentAreaFilled(false);
        btnBatalP3.setFocusable(false);
        btnBatalP3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClosehover.png"))); // NOI18N
        frameP3.getContentPane().add(btnBatalP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -10, 160, 130));

        lblBanyakGP3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakGP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakGP3.setText("1");
        frameP3.getContentPane().add(lblBanyakGP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 40, 60));

        btnMulaiP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOK.png"))); // NOI18N
        btnMulaiP3.setBorderPainted(false);
        btnMulaiP3.setContentAreaFilled(false);
        btnMulaiP3.setFocusable(false);
        btnMulaiP3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOKhover.png"))); // NOI18N
        frameP3.getContentPane().add(btnMulaiP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 300, 110));

        btnKurangGP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinus.png"))); // NOI18N
        btnKurangGP3.setBorderPainted(false);
        btnKurangGP3.setContentAreaFilled(false);
        btnKurangGP3.setFocusable(false);
        frameP3.getContentPane().add(btnKurangGP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 245, 60, 50));

        btnTambahGP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlus.png"))); // NOI18N
        btnTambahGP3.setBorderPainted(false);
        btnTambahGP3.setContentAreaFilled(false);
        btnTambahGP3.setFocusable(false);
        btnTambahGP3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlushover.png"))); // NOI18N
        frameP3.getContentPane().add(btnTambahGP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 245, 50, 50));

        btnKurangJRP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinus.png"))); // NOI18N
        btnKurangJRP3.setBorderPainted(false);
        btnKurangJRP3.setContentAreaFilled(false);
        btnKurangJRP3.setFocusable(false);
        frameP3.getContentPane().add(btnKurangJRP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 163, 60, 50));

        lblBanyakJRP3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakJRP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakJRP3.setText("1");
        frameP3.getContentPane().add(lblBanyakJRP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, 60));

        btnTambahJRP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlus.png"))); // NOI18N
        btnTambahJRP3.setBorderPainted(false);
        btnTambahJRP3.setContentAreaFilled(false);
        btnTambahJRP3.setFocusable(false);
        btnTambahJRP3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlushover.png"))); // NOI18N
        frameP3.getContentPane().add(btnTambahJRP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 163, 50, 50));

        lblBanyakJRP3Max.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakJRP3Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakJRP3Max.setText("/ 20");
        frameP3.getContentPane().add(lblBanyakJRP3Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 40, 60));

        lblBanyakGP4Max.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakGP4Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakGP4Max.setText("/  6");
        frameP3.getContentPane().add(lblBanyakGP4Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 40, 60));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tambahBahanProses3.png"))); // NOI18N
        frameP3.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 530));

        frameP4.setMinimumSize(new java.awt.Dimension(643, 530));
        frameP4.setUndecorated(true);
        frameP4.setResizable(false);
        frameP4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatalP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClose.png"))); // NOI18N
        btnBatalP4.setBorderPainted(false);
        btnBatalP4.setContentAreaFilled(false);
        btnBatalP4.setFocusable(false);
        btnBatalP4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBatalP4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBatalP4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isigudang/tier 1/tblClosehover.png"))); // NOI18N
        frameP4.getContentPane().add(btnBatalP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, -20, 150, 150));

        lblBanyakP4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP4.setText("1");
        frameP4.getContentPane().add(lblBanyakP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 40, 40));

        btnTambahP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlus.png"))); // NOI18N
        btnTambahP4.setBorderPainted(false);
        btnTambahP4.setContentAreaFilled(false);
        btnTambahP4.setFocusable(false);
        btnTambahP4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlushover.png"))); // NOI18N
        frameP4.getContentPane().add(btnTambahP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 50, 50));

        btnMulaiP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOK.png"))); // NOI18N
        btnMulaiP4.setBorderPainted(false);
        btnMulaiP4.setContentAreaFilled(false);
        btnMulaiP4.setFocusable(false);
        btnMulaiP4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblOKhover.png"))); // NOI18N
        frameP4.getContentPane().add(btnMulaiP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 290, 100));

        btnKurangP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinus.png"))); // NOI18N
        btnKurangP4.setBorderPainted(false);
        btnKurangP4.setContentAreaFilled(false);
        btnKurangP4.setDefaultCapable(false);
        btnKurangP4.setFocusable(false);
        btnKurangP4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinushover.png"))); // NOI18N
        frameP4.getContentPane().add(btnKurangP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 50));

        lblBanyakP5Max.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakP5Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP5Max.setText("/ 30");
        frameP4.getContentPane().add(lblBanyakP5Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 40, 40));

        btnKurangMinyak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinus.png"))); // NOI18N
        btnKurangMinyak.setBorderPainted(false);
        btnKurangMinyak.setContentAreaFilled(false);
        btnKurangMinyak.setDefaultCapable(false);
        btnKurangMinyak.setFocusable(false);
        btnKurangMinyak.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblMinushover.png"))); // NOI18N
        frameP4.getContentPane().add(btnKurangMinyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 245, 50, 50));

        lblBanyakMinyak.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakMinyak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakMinyak.setText("1");
        frameP4.getContentPane().add(lblBanyakMinyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 40, 40));

        lblBanyakP5Max1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblBanyakP5Max1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP5Max1.setText("/ 30");
        frameP4.getContentPane().add(lblBanyakP5Max1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 40, 40));

        btnTambahMinyak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlus.png"))); // NOI18N
        btnTambahMinyak.setBorderPainted(false);
        btnTambahMinyak.setContentAreaFilled(false);
        btnTambahMinyak.setFocusable(false);
        btnTambahMinyak.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tblPlushover.png"))); // NOI18N
        btnTambahMinyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMinyakActionPerformed(evt);
            }
        });
        frameP4.getContentPane().add(btnTambahMinyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 245, 50, 50));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tambah bahan/tambahBahanProses4.png"))); // NOI18N
        frameP4.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 530));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProses1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblproses1.png"))); // NOI18N
        btnProses1.setBorderPainted(false);
        btnProses1.setContentAreaFilled(false);
        btnProses1.setFocusable(false);
        btnProses1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProses1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblproses1hover.png"))); // NOI18N
        getContentPane().add(btnProses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 260, 220));

        btnProses4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblkompor.png"))); // NOI18N
        btnProses4.setBorderPainted(false);
        btnProses4.setContentAreaFilled(false);
        btnProses4.setFocusable(false);
        btnProses4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProses4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProses4.setMaximumSize(new java.awt.Dimension(1280, 720));
        btnProses4.setMinimumSize(new java.awt.Dimension(1280, 720));
        btnProses4.setPreferredSize(new java.awt.Dimension(1280, 720));
        btnProses4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblkomporHover.png"))); // NOI18N
        getContentPane().add(btnProses4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 250, 200));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/orang2.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/orang1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        btnProses3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblproses3.png"))); // NOI18N
        btnProses3.setBorderPainted(false);
        btnProses3.setContentAreaFilled(false);
        btnProses3.setFocusable(false);
        btnProses3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProses3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProses3.setMaximumSize(new java.awt.Dimension(1280, 720));
        btnProses3.setMinimumSize(new java.awt.Dimension(1280, 720));
        btnProses3.setPreferredSize(new java.awt.Dimension(1280, 720));
        btnProses3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblproses3hover.png"))); // NOI18N
        getContentPane().add(btnProses3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 300, 240));

        btnProses2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblproses2.png"))); // NOI18N
        btnProses2.setBorderPainted(false);
        btnProses2.setContentAreaFilled(false);
        btnProses2.setFocusable(false);
        btnProses2.setMaximumSize(new java.awt.Dimension(1280, 720));
        btnProses2.setMinimumSize(new java.awt.Dimension(1280, 720));
        btnProses2.setPreferredSize(new java.awt.Dimension(1280, 720));
        btnProses2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblproses2hover.png"))); // NOI18N
        getContentPane().add(btnProses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 340, 250));

        lblMarning.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblMarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarning.setText("marning");
        getContentPane().add(lblMarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 320, 70, 40));

        lblJagung.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJagung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagung.setText("jagung");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 70, 40));

        lblJagungBumbu.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJagungBumbu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagungBumbu.setText("jagung bumbu");
        getContentPane().add(lblJagungBumbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 250, 70, 40));

        lblJagungCuci.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJagungCuci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagungCuci.setText("jagung cuci");
        getContentPane().add(lblJagungCuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 120, 70, 40));

        lblJagungRendam.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJagungRendam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJagungRendam.setText("jagung rendam");
        getContentPane().add(lblJagungRendam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 70, 50));

        btnTambahKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblKaryawan.png"))); // NOI18N
        btnTambahKaryawan.setBorderPainted(false);
        btnTambahKaryawan.setContentAreaFilled(false);
        btnTambahKaryawan.setFocusable(false);
        btnTambahKaryawan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/tblKaryawanhover.png"))); // NOI18N
        getContentPane().add(btnTambahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, 200, 190));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tblKembali.png"))); // NOI18N
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setFocusable(false);
        btnKembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tblKembaliHover.png"))); // NOI18N
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        lblJumlahKaryawan.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJumlahKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahKaryawan.setText("Karyawan");
        getContentPane().add(lblJumlahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 380, 70, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/scoreboard.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/jagungSudahCuci.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/siapJual.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 210, 170));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/jagungsiappakai.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 160, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMinyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMinyakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahMinyakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pabrik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalP1;
    private javax.swing.JButton btnBatalP2;
    private javax.swing.JButton btnBatalP3;
    private javax.swing.JButton btnBatalP4;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKurangGP3;
    private javax.swing.JButton btnKurangJRP3;
    private javax.swing.JButton btnKurangMinyak;
    private javax.swing.JButton btnKurangP1;
    private javax.swing.JButton btnKurangP2;
    private javax.swing.JButton btnKurangP4;
    private javax.swing.JButton btnMulaiP1;
    private javax.swing.JButton btnMulaiP2;
    private javax.swing.JButton btnMulaiP3;
    private javax.swing.JButton btnMulaiP4;
    private javax.swing.JButton btnProses1;
    private javax.swing.JButton btnProses2;
    private javax.swing.JButton btnProses3;
    private javax.swing.JButton btnProses4;
    private javax.swing.JButton btnTambahGP3;
    private javax.swing.JButton btnTambahJRP3;
    private javax.swing.JButton btnTambahKaryawan;
    private javax.swing.JButton btnTambahMinyak;
    private javax.swing.JButton btnTambahP1;
    private javax.swing.JButton btnTambahP2;
    private javax.swing.JButton btnTambahP4;
    private javax.swing.JFrame frameP1;
    private javax.swing.JFrame frameP2;
    private javax.swing.JFrame frameP3;
    private javax.swing.JFrame frameP4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBanyakGP3;
    private javax.swing.JLabel lblBanyakGP4Max;
    private javax.swing.JLabel lblBanyakJRP3;
    private javax.swing.JLabel lblBanyakJRP3Max;
    private javax.swing.JLabel lblBanyakK1;
    private javax.swing.JLabel lblBanyakMinyak;
    private javax.swing.JLabel lblBanyakP1;
    private javax.swing.JLabel lblBanyakP2;
    private javax.swing.JLabel lblBanyakP4;
    private javax.swing.JLabel lblBanyakP5Max;
    private javax.swing.JLabel lblBanyakP5Max1;
    private javax.swing.JLabel lblJagung;
    private javax.swing.JLabel lblJagungBumbu;
    private javax.swing.JLabel lblJagungCuci;
    private javax.swing.JLabel lblJagungRendam;
    private javax.swing.JLabel lblJumlahKaryawan;
    private javax.swing.JLabel lblMarning;
    private javax.swing.JLabel lblMaxP2;
    // End of variables declaration//GEN-END:variables
}
