/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class sawah extends javax.swing.JFrame {

    /**
     * Creates new form sawah
     */
    public sawah() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnAir() {
        return btnAir;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnKotak1() {
        return btnKotak1;
    }

    public JButton getBtnKotak2() {
        return btnKotak2;
    }

    public JButton getBtnKotak3() {
        return btnKotak3;
    }

    public JButton getBtnKotak4() {
        return btnKotak4;
    }

    public JButton getBtnKotak5() {
        return btnKotak5;
    }

    public JButton getBtnKotak6() {
        return btnKotak6;
    }

    public JLabel getLblBibit() {
        return lblBibit;
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }

    public JLabel getLblNotif() {
        return lblNotif;
    }

    public JLabel getLblNotif1() {
        return lblNotif1;
    }

    public JLabel getLblNotif2() {
        return lblNotif2;
    }

    public JLabel getLblNotif3() {
        return lblNotif3;
    }

    public JLabel getLblNotif4() {
        return lblNotif4;
    }

    public JLabel getLblNotif5() {
        return lblNotif5;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotif5 = new javax.swing.JLabel();
        lblNotif4 = new javax.swing.JLabel();
        lblNotif3 = new javax.swing.JLabel();
        lblNotif2 = new javax.swing.JLabel();
        lblNotif1 = new javax.swing.JLabel();
        lblNotif = new javax.swing.JLabel();
        btnAir = new javax.swing.JButton();
        btnKotak6 = new javax.swing.JButton();
        btnKotak5 = new javax.swing.JButton();
        btnKotak4 = new javax.swing.JButton();
        btnKotak3 = new javax.swing.JButton();
        btnKotak2 = new javax.swing.JButton();
        btnKotak1 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblBibit = new javax.swing.JLabel();
        lblJagung = new javax.swing.JLabel();
        statusBar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNotif5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif5.setToolTipText("");
        getContentPane().add(lblNotif5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 260, 230));

        lblNotif4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif4.setToolTipText("");
        getContentPane().add(lblNotif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 260, 230));

        lblNotif3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif3.setToolTipText("");
        getContentPane().add(lblNotif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 260, 230));

        lblNotif2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif2.setToolTipText("");
        getContentPane().add(lblNotif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 260, 230));

        lblNotif1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif1.setToolTipText("");
        getContentPane().add(lblNotif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 260, 230));

        lblNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif.setToolTipText("");
        getContentPane().add(lblNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 260, 230));

        btnAir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tblSiram.png"))); // NOI18N
        btnAir.setBorderPainted(false);
        btnAir.setContentAreaFilled(false);
        btnAir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAir.setFocusable(false);
        btnAir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tblSiram hover.png"))); // NOI18N
        getContentPane().add(btnAir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 510, -1, 210));

        btnKotak6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tanah kosong.png"))); // NOI18N
        btnKotak6.setBorderPainted(false);
        btnKotak6.setContentAreaFilled(false);
        btnKotak6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak6.setFocusable(false);
        btnKotak6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 288, 290, 390));

        btnKotak5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tanah kosong.png"))); // NOI18N
        btnKotak5.setBorderPainted(false);
        btnKotak5.setContentAreaFilled(false);
        btnKotak5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak5.setFocusable(false);
        btnKotak5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 288, 290, 390));

        btnKotak4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tanah kosong.png"))); // NOI18N
        btnKotak4.setBorderPainted(false);
        btnKotak4.setContentAreaFilled(false);
        btnKotak4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak4.setFocusable(false);
        btnKotak4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 288, 290, 390));

        btnKotak3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tanah kosong.png"))); // NOI18N
        btnKotak3.setBorderPainted(false);
        btnKotak3.setContentAreaFilled(false);
        btnKotak3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak3.setFocusable(false);
        btnKotak3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(963, 98, 300, 360));

        btnKotak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tanah kosong.png"))); // NOI18N
        btnKotak2.setBorderPainted(false);
        btnKotak2.setContentAreaFilled(false);
        btnKotak2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak2.setFocusable(false);
        btnKotak2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 97, 290, 360));

        btnKotak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tanah kosong.png"))); // NOI18N
        btnKotak1.setBorderPainted(false);
        btnKotak1.setContentAreaFilled(false);
        btnKotak1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak1.setDefaultCapable(false);
        btnKotak1.setFocusable(false);
        btnKotak1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 98, 290, 360));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tblKembali.png"))); // NOI18N
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setFocusable(false);
        btnKembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tblKembaliHover.png"))); // NOI18N
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 60));

        lblBibit.setFont(new java.awt.Font("Bw Surco DEMO", 1, 18)); // NOI18N
        lblBibit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBibit.setText("Bibit");
        getContentPane().add(lblBibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 120, 40));

        lblJagung.setFont(new java.awt.Font("Bw Surco DEMO", 1, 18)); // NOI18N
        lblJagung.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJagung.setText("Jagung");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 120, 40));

        statusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/statusBarSawah.png"))); // NOI18N
        getContentPane().add(statusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/backgroundsawah.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sawah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAir;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKotak1;
    private javax.swing.JButton btnKotak2;
    private javax.swing.JButton btnKotak3;
    private javax.swing.JButton btnKotak4;
    private javax.swing.JButton btnKotak5;
    private javax.swing.JButton btnKotak6;
    private javax.swing.JLabel lblBibit;
    private javax.swing.JLabel lblJagung;
    private javax.swing.JLabel lblNotif;
    private javax.swing.JLabel lblNotif1;
    private javax.swing.JLabel lblNotif2;
    private javax.swing.JLabel lblNotif3;
    private javax.swing.JLabel lblNotif4;
    private javax.swing.JLabel lblNotif5;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
