/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class sawah extends javax.swing.JFrame {

    /**
     * Creates new form sawah
     */
    public sawah() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnAir() {
        return btnAir;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnKotak1() {
        return btnKotak1;
    }

    public JButton getBtnKotak2() {
        return btnKotak2;
    }

    public JButton getBtnKotak3() {
        return btnKotak3;
    }

    public JButton getBtnKotak4() {
        return btnKotak4;
    }

    public JButton getBtnKotak5() {
        return btnKotak5;
    }

    public JButton getBtnKotak6() {
        return btnKotak6;
    }

    public JLabel getLblBibit() {
        return lblBibit;
    }

    public JLabel getLblJagung() {
        return lblJagung;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAir = new javax.swing.JButton();
        btnKotak6 = new javax.swing.JButton();
        btnKotak5 = new javax.swing.JButton();
        btnKotak4 = new javax.swing.JButton();
        btnKotak3 = new javax.swing.JButton();
        btnKotak2 = new javax.swing.JButton();
        btnKotak1 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblBibit = new javax.swing.JLabel();
        lblJagung = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAir.setText("Air");
        btnAir.setFocusable(false);
        getContentPane().add(btnAir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 540, 120, 120));

        btnKotak6.setText("Kotak 6");
        btnKotak6.setFocusable(false);
        getContentPane().add(btnKotak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 210, 210));

        btnKotak5.setText("Kotak 5");
        btnKotak5.setFocusable(false);
        getContentPane().add(btnKotak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 210, 210));

        btnKotak4.setText("Kotak 4");
        btnKotak4.setFocusable(false);
        getContentPane().add(btnKotak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 210, 210));

        btnKotak3.setText("Kotak 3");
        btnKotak3.setFocusable(false);
        getContentPane().add(btnKotak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 210, 210));

        btnKotak2.setText("Kotak 2");
        btnKotak2.setFocusable(false);
        getContentPane().add(btnKotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 210, 210));

        btnKotak1.setText("Kotak 1");
        btnKotak1.setFocusable(false);
        getContentPane().add(btnKotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 210, 210));

        btnKembali.setText("Kembali");
        btnKembali.setFocusable(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 60));

        lblBibit.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblBibit.setText("Bibit");
        getContentPane().add(lblBibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 70, 30));

        lblJagung.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblJagung.setText("Jagung");
        getContentPane().add(lblJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 70, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gambar Orang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 140, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sawah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAir;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKotak1;
    private javax.swing.JButton btnKotak2;
    private javax.swing.JButton btnKotak3;
    private javax.swing.JButton btnKotak4;
    private javax.swing.JButton btnKotak5;
    private javax.swing.JButton btnKotak6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBibit;
    private javax.swing.JLabel lblJagung;
    // End of variables declaration//GEN-END:variables
}
