/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class tambahKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form tambahKaryawan
     */
    public tambahKaryawan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnKurangP1() {
        return btnKurangP1;
    }

    public JButton getBtnKurangP2() {
        return btnKurangP2;
    }

    public JButton getBtnKurangP3() {
        return btnKurangP3;
    }

    public JButton getBtnKurangP4() {
        return btnKurangP4;
    }

    public JButton getBtnTambahKaryawan() {
        return btnTambahKaryawan;
    }

    public JButton getBtnTambahP1() {
        return btnTambahP1;
    }

    public JButton getBtnTambahP2() {
        return btnTambahP2;
    }

    public JButton getBtnTambahP3() {
        return btnTambahP3;
    }

    public JButton getBtnTambahP4() {
        return btnTambahP4;
    }

    public JLabel getLblBanyakP1() {
        return lblBanyakP1;
    }

    public JLabel getLblBanyakP2() {
        return lblBanyakP2;
    }

    public JLabel getLblBanyakP3() {
        return lblBanyakP3;
    }

    public JLabel getLblBanyakP4() {
        return lblBanyakP4;
    }

    public JLabel getLblJumlahKaryawan() {
        return lblJumlahKaryawan;
    }

    public JLabel getLblUang() {
        return lblUang;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBatal = new javax.swing.JButton();
        lblUang = new javax.swing.JLabel();
        lblJumlahKaryawan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBanyakP4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBanyakP1 = new javax.swing.JLabel();
        lblBanyakP2 = new javax.swing.JLabel();
        lblBanyakP3 = new javax.swing.JLabel();
        btnKurangP3 = new javax.swing.JButton();
        btnTambahP3 = new javax.swing.JButton();
        btnKurangP2 = new javax.swing.JButton();
        btnTambahP2 = new javax.swing.JButton();
        btnKurangP1 = new javax.swing.JButton();
        btnTambahP1 = new javax.swing.JButton();
        btnTambahP4 = new javax.swing.JButton();
        btnKurangP4 = new javax.swing.JButton();
        btnTambahKaryawan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatal.setText("Batal");
        btnBatal.setFocusable(false);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 60));

        lblUang.setText("Uang");
        getContentPane().add(lblUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 70, 30));

        lblJumlahKaryawan.setText("karyawan");
        getContentPane().add(lblJumlahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 70, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proses 4");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 150, 120, 50));

        lblBanyakP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP4.setText("Banyak");
        getContentPane().add(lblBanyakP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 120, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Proses 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 120, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Proses 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 120, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Proses 4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 150, 120, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Proses 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 120, 50));

        lblBanyakP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP1.setText("Banyak");
        getContentPane().add(lblBanyakP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 50));

        lblBanyakP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP2.setText("Banyak");
        getContentPane().add(lblBanyakP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 120, 50));

        lblBanyakP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanyakP3.setText("Banyak");
        getContentPane().add(lblBanyakP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 120, 50));

        btnKurangP3.setText("-");
        btnKurangP3.setFocusable(false);
        getContentPane().add(btnKurangP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 80, 60));

        btnTambahP3.setText("+");
        btnTambahP3.setFocusable(false);
        getContentPane().add(btnTambahP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 80, 60));

        btnKurangP2.setText("-");
        btnKurangP2.setFocusable(false);
        getContentPane().add(btnKurangP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 80, 60));

        btnTambahP2.setText("+");
        btnTambahP2.setFocusable(false);
        getContentPane().add(btnTambahP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 80, 60));

        btnKurangP1.setText("-");
        btnKurangP1.setFocusable(false);
        getContentPane().add(btnKurangP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 80, 60));

        btnTambahP1.setText("+");
        btnTambahP1.setFocusable(false);
        getContentPane().add(btnTambahP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, 60));

        btnTambahP4.setText("+");
        btnTambahP4.setFocusable(false);
        getContentPane().add(btnTambahP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 260, 80, 60));

        btnKurangP4.setText("-");
        btnKurangP4.setFocusable(false);
        getContentPane().add(btnKurangP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 410, 80, 60));

        btnTambahKaryawan.setText("Tambah Karyawan");
        btnTambahKaryawan.setFocusable(false);
        getContentPane().add(btnTambahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 370, 80));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Harga/orang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 90, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Harga/orang");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 30));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Harga/orang");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 90, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Harga/orang");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKurangP1;
    private javax.swing.JButton btnKurangP2;
    private javax.swing.JButton btnKurangP3;
    private javax.swing.JButton btnKurangP4;
    private javax.swing.JButton btnTambahKaryawan;
    private javax.swing.JButton btnTambahP1;
    private javax.swing.JButton btnTambahP2;
    private javax.swing.JButton btnTambahP3;
    private javax.swing.JButton btnTambahP4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBanyakP1;
    private javax.swing.JLabel lblBanyakP2;
    private javax.swing.JLabel lblBanyakP3;
    private javax.swing.JLabel lblBanyakP4;
    private javax.swing.JLabel lblJumlahKaryawan;
    private javax.swing.JLabel lblUang;
    // End of variables declaration//GEN-END:variables
}
