/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class tokoPenjualanProduk extends javax.swing.JFrame {

    /**
     * Creates new form tokoPenjualanProduk
     */
    public tokoPenjualanProduk() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }

    public JLabel getLblMarning() {
        return lblMarning;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnMulaiJual() {
        return btnMulaiJual;
    }

    public JLabel getItem1Value() {
        return lblKoin;
    }

    public JLabel getItem2Value() {
        return lblMarning;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblKoin = new javax.swing.JLabel();
        btnMulaiJual = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarning.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblMarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarning.setText("Marning");
        getContentPane().add(lblMarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 70, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOKO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 130, 60));

        lblKoin.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKoin.setText("Koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 70, 40));

        btnMulaiJual.setText("BUKA TOKO");
        btnMulaiJual.setFocusable(false);
        getContentPane().add(btnMulaiJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 60));

        btnKembali.setText("KEMBALI");
        btnKembali.setFocusable(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tokoPenjualanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tokoPenjualanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tokoPenjualanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tokoPenjualanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tokoPenjualanProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnMulaiJual;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblKoin;
    private javax.swing.JLabel lblMarning;
    // End of variables declaration//GEN-END:variables
}
